### ISSUE TITLE
Is it still being maintained?

### ISSUE THREAD

**Issue by esc** [seanh/dotfilemanager#2]
I was wondering, is this still being maintained?

**Comment by seanh** [comment]
Hi @esc, actually no, I stopped using dotfilemanager recently and moved to using GNU Stow to manage my dotfiles. I should update the dotfilemanager README. There are lots of dotfile management tools out there now, and lots of blog posts about using Stow as one too.

Dotfilemanager worked perfectly for me for several years and doesn't have any bugs (that I'm aware of) or any missing features that I wanted to add to it. I just found that Stow works in a way that I like better.

If you're interested in taking over maintenance of dotfilemanager, please fork it.

**Comment by esc** [comment]
@seanh cool, thanks for the update. I started writing my own now actually. :)
