### ISSUE TITLE
Why require .dotfiles folder name?

### ISSUE THREAD

**Issue by teodorlu** [seanh/dotfilemanager#3]
Hello!

Thanks for releasing this tool.

I keep my dotfiles in `~/git/dotfiles/HOME/`. _dotfilemanager_ requires me to have the dotfiles stored in a folder named exactly `dotfiles`. I'd like to keep this structure. Specifically:

```
teodorlu@XPS13 ~/git/dotfiles/HOME (git)-[master] % dotfilemanager ~ .
TO_DIR /home/teodorlu/.dotfiles is not a directory!
Usage:

dotfilemanager link|tidy|report [FROM_DIR [TO_DIR]]
    
Commands:
   link -- make symlinks in FROM_DIR to files and directories in TO_DIR
   tidy -- remove broken symlinks from FROM_DIR
   report -- report on symlinks in FROM_DIR and files and directories in TO_DIR
   
FROM_DIR defaults to ~ and TO_DIR defaults to ~/.dotfiles.
```

Thought I'd leave the feedback.

Again, thanks!

**Comment by seanh** [comment]
Hey, you missed the action (`link|tidy|report`) from your command. Try: `dotfilemanager link ~ .`. Or if your dotfiles are in `~/git/dotfiles/HOME/` then it should be `dotfilemanager link ~ ~/git/dotfiles/HOME/`.

**Comment by teodorlu** [comment]
You're right. Everything works, my blunder.

Thanks again for the tool!

**Comment by seanh** [comment]
Glad someone's using it! I haven't used it myself for a while, but I did use it for many years and never had any problems with it
